'use client';
import { ImagePlus, Send } from 'lucide-react';
import { ChangeEvent, FormEvent, useState } from 'react';
type ContactFormProps = { vehicle?: string; type?: 'contact' | 'sell' | 'vehicle'; };
export function ContactForm({ vehicle, type = 'contact' }: ContactFormProps) {
  const [sent, setSent] = useState(false);
  const [photoNames, setPhotoNames] = useState<string[]>([]);
  function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); }
  function handlePhotos(event: ChangeEvent<HTMLInputElement>) {
    setPhotoNames(Array.from(event.target.files ?? []).map((file) => file.name));
  }
  return <form onSubmit={handleSubmit} className="luxury-panel rounded-sm p-5 md:p-7"><h2 className="font-display text-2xl font-bold text-white">{type === 'sell' ? 'Request a valuation' : type === 'vehicle' ? 'Enquire about this vehicle' : 'Send us a message'}</h2><div className="mt-6 grid gap-4">{type === 'sell' && <><input className="input-field uppercase" required placeholder="Registration" name="registration" /><input className="input-field" required placeholder="Mileage" name="mileage" type="number" /><label className="block rounded-sm border border-dashed border-gold/35 bg-black/30 p-5 text-sm text-white/66 transition hover:border-gold/70"><span className="flex items-center gap-3 font-bold text-white"><ImagePlus className="text-gold" size={20} />Upload car photos</span><span className="mt-2 block text-white/50">Add exterior, interior, wheels, service history or damage photos. Multiple images accepted.</span><input className="sr-only" name="photos" type="file" accept="image/*" multiple onChange={handlePhotos} /></label>{photoNames.length > 0 && <div className="rounded-sm border border-white/10 bg-white/[.035] p-4 text-sm text-white/64"><p className="font-bold text-gold">{photoNames.length} photo{photoNames.length === 1 ? '' : 's'} selected</p><p className="mt-2 truncate">{photoNames.slice(0, 3).join(', ')}{photoNames.length > 3 ? '...' : ''}</p></div>}</>}{vehicle && <input className="input-field" name="vehicle" value={vehicle} readOnly />}<input className="input-field" required placeholder="Name" name="name" /><input className="input-field" required placeholder="Phone" name="phone" type="tel" /><input className="input-field" required placeholder="Email" name="email" type="email" />{type !== 'sell' && <textarea className="input-field min-h-32 resize-none" placeholder="How can we help?" name="message" />}</div><button className="btn-primary mt-5 w-full" type="submit"><Send size={18} />Submit enquiry</button>{sent && <p className="mt-4 rounded-sm border border-gold/30 bg-gold/10 p-3 text-sm text-gold">Thanks. Your enquiry has been captured and is ready to connect to your CRM, email provider or photo upload storage.</p>}</form>;
}
