'use client';
import { Calculator } from 'lucide-react';
import { useMemo, useState } from 'react';
import { formatCurrency } from '@/lib/vehicles';
export function FinanceCalculator({ initialPrice = 35000 }: { initialPrice?: number }) {
  const [price, setPrice] = useState(initialPrice); const [deposit, setDeposit] = useState(Math.round(initialPrice * 0.1)); const [term, setTerm] = useState(48); const [apr, setApr] = useState(10.9);
  const monthly = useMemo(() => { const principal = Math.max(price - deposit, 0); const monthlyRate = apr / 100 / 12; if (principal === 0) return 0; return (principal * monthlyRate) / (1 - Math.pow(1 + monthlyRate, -term)); }, [price, deposit, term, apr]);
  return <div className="luxury-panel rounded-sm p-5 md:p-7"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-sm bg-gold text-black"><Calculator size={22} /></span><div><h3 className="text-xl font-black text-white">Finance calculator</h3><p className="text-sm text-white/55">Indicative figures only, subject to status.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-white/72">Vehicle price<input className="input-field mt-2" type="number" value={price} onChange={(event) => setPrice(Number(event.target.value))} /></label><label className="text-sm font-bold text-white/72">Deposit<input className="input-field mt-2" type="number" value={deposit} onChange={(event) => setDeposit(Number(event.target.value))} /></label><label className="text-sm font-bold text-white/72">Term<select className="input-field mt-2" value={term} onChange={(event) => setTerm(Number(event.target.value))}><option value="36">36 months</option><option value="48">48 months</option><option value="60">60 months</option></select></label><label className="text-sm font-bold text-white/72">APR<input className="input-field mt-2" type="number" step="0.1" value={apr} onChange={(event) => setApr(Number(event.target.value))} /></label></div><div className="mt-6 rounded-sm border border-gold/30 bg-black/45 p-5"><p className="text-sm uppercase tracking-[0.2em] text-white/48">Estimated monthly payment</p><p className="mt-2 text-4xl font-black text-gold">{formatCurrency(monthly)}</p></div></div>;
}
