import type { Metadata } from 'next';
import { MessageCircle } from 'lucide-react';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { ContactForm } from '@/components/ContactForm';
import { FinanceCalculator } from '@/components/FinanceCalculator';
import { PageHeader } from '@/components/PageHeader';
import { site } from '@/lib/site';
import { formatCurrency, formatNumber, getVehicleBySlug, vehicles } from '@/lib/vehicles';
type VehicleParams = { slug: string };
export function generateStaticParams() { return vehicles.map((vehicle) => ({ slug: vehicle.slug })); }
export async function generateMetadata({ params }: { params: Promise<VehicleParams> }): Promise<Metadata> { const { slug } = await params; const vehicle = getVehicleBySlug(slug); if (!vehicle) return { title: 'Vehicle Not Found' }; return { title: `${vehicle.make} ${vehicle.model} ${vehicle.derivative}`, description: `${vehicle.year} ${vehicle.make} ${vehicle.model} for sale at MA Motors. ${formatCurrency(vehicle.price)}, ${formatNumber(vehicle.mileage)} miles.` }; }
export default async function VehicleDetailsPage({ params }: { params: Promise<VehicleParams> }) {
  const { slug } = await params; const vehicle = getVehicleBySlug(slug); if (!vehicle) notFound();
  const specs = [['Mileage', `${formatNumber(vehicle.mileage)} miles`], ['Registration', vehicle.registration], ['Engine size', vehicle.engineSize], ['Fuel type', vehicle.fuelType], ['Transmission', vehicle.transmission], ['Body type', vehicle.bodyType], ['Colour', vehicle.color], ['Doors', String(vehicle.doors)], ['Seats', String(vehicle.seats)]];
  return <main><PageHeader eyebrow="Vehicle Details" title={`${vehicle.make} ${vehicle.model}`} copy={`${vehicle.derivative} - ${formatCurrency(vehicle.price)} - ${vehicle.year} - ${formatNumber(vehicle.mileage)} miles`} /><section className="section-pad bg-night"><div className="container-shell grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><div><div className="relative aspect-[16/10] overflow-hidden rounded-sm border border-white/10 bg-charcoal"><Image src={vehicle.images[0]} alt={`${vehicle.make} ${vehicle.model}`} fill priority sizes="(min-width: 1024px) 65vw, 100vw" className="object-cover" /></div><div className="mt-4 grid grid-cols-3 gap-4">{vehicle.images.slice(1).map((image, index) => <div key={image} className="relative aspect-[16/10] overflow-hidden rounded-sm border border-white/10 bg-charcoal"><Image src={image} alt={`${vehicle.make} ${vehicle.model} gallery ${index + 2}`} fill sizes="33vw" className="object-cover" /></div>)}</div><div className="mt-8 luxury-panel rounded-sm p-6"><h2 className="font-display text-3xl font-bold text-white">Specification</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{specs.map(([label, value]) => <div key={label} className="rounded-sm border border-white/10 bg-black/35 p-4"><p className="text-xs uppercase tracking-[0.2em] text-white/45">{label}</p><p className="mt-2 font-bold text-white">{value}</p></div>)}</div><h3 className="mt-8 text-xl font-black text-white">Highlights</h3><div className="mt-4 flex flex-wrap gap-2">{vehicle.highlights.map((item) => <span key={item} className="rounded-sm border border-gold/25 bg-gold/10 px-3 py-2 text-sm text-gold">{item}</span>)}</div><h3 className="mt-8 text-xl font-black text-white">Features</h3><ul className="mt-4 grid gap-2 sm:grid-cols-2">{vehicle.features.map((item) => <li key={item} className="text-white/68">• {item}</li>)}</ul><p className="mt-8 leading-8 text-white/66">{vehicle.description}</p></div></div><aside className="space-y-6 lg:sticky lg:top-28 lg:self-start"><div className="rounded-sm border border-gold/30 bg-black p-6"><p className="text-sm uppercase tracking-[0.24em] text-white/48">Price</p><p className="mt-2 text-4xl font-black text-gold">{formatCurrency(vehicle.price)}</p><a href={`https://wa.me/${site.whatsapp}?text=I'm%20interested%20in%20the%20${encodeURIComponent(`${vehicle.make} ${vehicle.model}`)}`} target="_blank" rel="noreferrer" className="btn-primary mt-5 w-full"><MessageCircle size={19} />WhatsApp us</a></div><FinanceCalculator initialPrice={vehicle.price} /><ContactForm type="vehicle" vehicle={`${vehicle.year} ${vehicle.make} ${vehicle.model} ${vehicle.derivative}`} /></aside></div></section></main>;
}
