import { Vehicle } from '@/types/vehicle';

export const vehicles: Vehicle[] = [
  {
    slug: 'audi-a3-sportback-black-35-tdi',
    make: 'Audi',
    model: 'A3 Sportback',
    derivative: '35 TDI S line',
    price: 19995,
    year: 2020,
    mileage: 42000,
    registration: 'KN70 UJM',
    engineSize: '2.0L',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'Hatchback',
    color: 'Mythos Black',
    doors: 5,
    seats: 5,
    images: ['/images/stock/audi-a3-black-front.jpg', '/images/stock/audi-a3-black-rear.jpg'],
    highlights: ['S line styling', 'Digital cockpit', 'Privacy glass', 'Strong specification'],
    features: ['Apple CarPlay', 'Bluetooth audio', 'Parking sensors', 'Cruise control', 'LED headlights', 'Drive select'],
    description: 'A sharp black Audi A3 Sportback with a clean look, premium finish and strong S line specification.'
  },
  {
    slug: 'volvo-xc90-r-design',
    make: 'Volvo',
    model: 'XC90',
    derivative: 'R-Design AWD',
    price: 29995,
    year: 2018,
    mileage: 69000,
    registration: 'Private plate shown',
    engineSize: '2.0L',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Onyx Black',
    doors: 5,
    seats: 7,
    images: ['/images/stock/volvo-xc90-front.jpg'],
    highlights: ['7 seats', 'R-Design styling', 'Panoramic roof', 'Large family SUV'],
    features: ['Leather interior', 'Navigation', 'Reversing camera', 'Heated seats', 'Digital dash', 'Premium audio'],
    description: 'A premium seven-seat Volvo XC90 with strong road presence, family practicality and a clean professional presentation.'
  },
  {
    slug: 'audi-rs4-avant-quattro',
    make: 'Audi',
    model: 'RS4 Avant',
    derivative: '4.2 FSI quattro',
    price: 24995,
    year: 2007,
    mileage: 78000,
    registration: 'AR06 FWL',
    engineSize: '4.2L',
    fuelType: 'Petrol',
    transmission: 'Manual',
    bodyType: 'Estate',
    color: 'Phantom Black',
    doors: 5,
    seats: 5,
    images: ['/images/stock/audi-rs4-rear.jpg'],
    highlights: ['V8 performance', 'Quattro AWD', 'RS styling', 'Estate practicality'],
    features: ['Sports seats', 'Dual exhausts', 'Climate control', 'Alloy wheels', 'Xenon headlights', 'Performance brakes'],
    description: 'A desirable Audi RS4 Avant combining classic V8 character with all-weather quattro performance.'
  },
  {
    slug: 'audi-sq7-quattro-black-edition',
    make: 'Audi',
    model: 'SQ7',
    derivative: 'quattro Black Edition',
    price: 37995,
    year: 2017,
    mileage: 64000,
    registration: 'Private plate shown',
    engineSize: '4.0L',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Orca Black',
    doors: 5,
    seats: 7,
    images: ['/images/stock/audi-sq7-rear.jpg'],
    highlights: ['7 seats', 'SQ7 performance', 'Black styling', 'Quad exhausts'],
    features: ['Air suspension', 'Virtual cockpit', 'Parking sensors', 'Heated seats', 'Power tailgate', 'Navigation'],
    description: 'A powerful luxury SUV with seven-seat practicality, premium equipment and a commanding black-on-black look.'
  },
  {
    slug: 'bmw-330d-m-sport-touring',
    make: 'BMW',
    model: '330d Touring',
    derivative: 'M Sport Auto',
    price: 15995,
    year: 2016,
    mileage: 76000,
    registration: 'FG64 LNV',
    engineSize: '3.0L',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'Estate',
    color: 'Carbon Black',
    doors: 5,
    seats: 5,
    images: ['/images/stock/bmw-330d-front.jpg', '/images/stock/bmw-330d-rear.jpg', '/images/stock/bmw-330d-rear-side.jpg'],
    highlights: ['M Sport package', 'Touring practicality', 'Panoramic roof', 'Strong 3.0 diesel'],
    features: ['Heated seats', 'Navigation', 'Parking sensors', 'Bluetooth', 'M Sport wheels', 'Cruise control'],
    description: 'A refined BMW 330d Touring with strong performance, useful estate space and smart M Sport styling.'
  },
  {
    slug: 'audi-a3-sportback-grey-s-line',
    make: 'Audi',
    model: 'A3 Sportback',
    derivative: 'S line',
    price: 12995,
    year: 2015,
    mileage: 72000,
    registration: 'GK15 ZRC',
    engineSize: '2.0L',
    fuelType: 'Diesel',
    transmission: 'Manual',
    bodyType: 'Hatchback',
    color: 'Daytona Grey',
    doors: 5,
    seats: 5,
    images: ['/images/stock/audi-a3-grey-front.jpg'],
    highlights: ['S line styling', 'Grey metallic paint', 'Economical hatchback', 'Clean presentation'],
    features: ['Bluetooth', 'Climate control', 'Alloy wheels', 'Parking sensors', 'DAB radio', 'Cruise control'],
    description: 'A smart grey Audi A3 Sportback with a clean look, efficient running costs and desirable S line styling.'
  },
  {
    slug: 'bmw-3-series-m-sport-saloon',
    make: 'BMW',
    model: '3 Series',
    derivative: 'M Sport Saloon',
    price: 11995,
    year: 2013,
    mileage: 83000,
    registration: 'LR13 PGY',
    engineSize: '2.0L',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'Saloon',
    color: 'Black Sapphire',
    doors: 4,
    seats: 5,
    images: ['/images/stock/bmw-3-series-front.jpg'],
    highlights: ['M Sport styling', 'Black alloy wheels', 'Automatic gearbox', 'Sport saloon look'],
    features: ['Navigation', 'Bluetooth', 'Parking sensors', 'Climate control', 'Sport seats', 'Cruise control'],
    description: 'A black BMW 3 Series M Sport saloon with strong kerb appeal, black wheels and a clean professional presentation.'
  }
];

export const makes = Array.from(new Set(vehicles.map((vehicle) => vehicle.make))).sort();
export const models = Array.from(new Set(vehicles.map((vehicle) => vehicle.model))).sort();
export function getVehicleBySlug(slug: string) { return vehicles.find((vehicle) => vehicle.slug === slug); }
export function formatCurrency(value: number) { return new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP', maximumFractionDigits: 0 }).format(value); }
export function formatNumber(value: number) { return new Intl.NumberFormat('en-GB').format(value); }
